LIBSSH2_ERROR_EAGAIN = -37
LIBSSH2_KNOWNHOST_TYPE_PLAIN = 1
LIBSSH2_KNOWNHOST_FILE_OPENSSH = 1
LIBSSH2_KNOWNHOST_KEYENC_RAW = 1 << 16
LIBSSH2_SESSION_BLOCK_INBOUND = 1
LIBSSH2_SESSION_BLOCK_OUTBOUND = 2

LIBSSH2_FXF_READ = 0x1
LIBSSH2_FXF_WRITE = 0x2
LIBSSH2_FXF_APPEND = 0x4
LIBSSH2_FXF_CREAT = 0x8
LIBSSH2_FXF_TRUNC = 0x10
LIBSSH2_FXF_EXCL = 0x20

LIBSSH2_SFTP_OPENFILE = 0
LIBSSH2_SFTP_OPENDIR = 1
