LIBSSH2_ERROR_EAGAIN = -37
LIBSSH2_KNOWNHOST_TYPE_PLAIN = 1
LIBSSH2_KNOWNHOST_FILE_OPENSSH = 1
LIBSSH2_KNOWNHOST_KEYENC_RAW = 1 << 16
LIBSSH2_SESSION_BLOCK_INBOUND = 1
LIBSSH2_SESSION_BLOCK_OUTBOUND = 2
